package.json
public/index.html
server/index.js

added in deque pattern library and added some semicolons also removed bootstrap

---

client/components/UserDeckList.jsx
client/store/userDeckList.js
server/api/users.js

FIX(userDeckListView): deck list view working yay

---

client/components/ReplSlideFormHO.jsx
client/store/deck.js
server/db/models/deck.js
server/db/models/slide.js
test/db/slide.spec.js

Revise slide and deck models

---

client/index.jsx

Closes #53 
It kept saying it couldn't find the module with require so switched to import. Also it's more consistent with file.

changed require to import in client/index.jsx

---

test/api/users.spec.js

Api tests #17

---

README.md

FEAT: readMe updated

---

client/components/NewDeckForm.jsx
client/components/UserDeckList.jsx

new deck form now reflects the current deck model
the user deck list takes you to the new deck form

UPDATE: new deck form & user deck list

---

.eslintrc.json
client/components/Runkit.jsx
client/components/SlideView1.jsx
client/components/SlideView2.jsx
client/components/SlideView3.jsx
client/components/SlideView4.jsx
client/components/SlideView5.jsx
client/components/SlideViewFrame.jsx
client/components/index.jsx
client/index.jsx
client/index.scss
client/routes.jsx
package.json
server/db/models/slide.js

Create slide view frame and rejigger lots of other things, accordingly

---

client/components/NavBar.jsx
client/components/NewDeckForm.jsx
client/components/UserDeckList.jsx
client/components/main.jsx
client/index.jsx
client/routes.jsx

pulls navbar into its own component, fixes some form behavior in new decks, and loading behavior in the interminable user deck list view because the unmovable mover hates me 
Closes #61

Nav bar adventures #61

---

server/db/models/slide.js

tiny PR for the slide model DONT FORGET TO FORCE TRUE YR DATABASE AFTER THIS YALL

UPDATE(slide model): text broken up

---

client/components/DeckOverview.jsx
client/components/index.jsx
client/index.jsx
client/routes.jsx
client/store/deck.js
client/store/slide.js
server/api/decks.js
server/api/index.js
server/db/models/slide.js

Deck overview #55

---

client/components/DeckOverview.jsx
server/api/decks.js

added button for add slide and fixed component for when no slides exist

---

client/components/SlideView1.jsx
client/components/SlideView2.jsx
client/components/SlideView3.jsx
client/components/SlideView4.jsx
client/components/SlideView5.jsx
client/components/SlideViewFrame.jsx

added markdown rendering to slide templates

---

client/components/main.jsx
client/store/index.js
client/store/showNavBar.js

Live hide navbar #77

---

client/components/SlideViewLive.jsx
client/components/index.jsx
client/routes.jsx
client/store/slide.js
server/api/decks.js

Get slides #79

---

client/store/slide.js
server/api/slides.js

FIX(slide): Make PUT /api/slide/:slideId return the updated slide

---

client/components/EditSlideForm.jsx
client/store/slide.js

FEAT(slide): Notify user when a slide gets successfully saved

---

client/components/SlideViewLive.jsx

fixed navbar disappearing act

---

client/components/Runkit.jsx

runkit takes in code props

---

client/components/DeckOverview.jsx
client/index.scss

fixed slide edit buttons on deck overview

---

server/api/decks.js

added in eager loading to get deck method

---

client/components/DeckOverview.jsx

fixed small incorrect call in componentDidMount

---

client/components/EditSlideForm.jsx
client/components/NewSlideButton.jsx
client/components/index.jsx
client/store/slide.js

YOU CAN MAKE A NEW SLIDE

---

client/components/SlideViewLive.jsx

made changes to live view to use deck loading the slides

---

client/components/EditSlideForm.jsx
client/components/NewDeckForm.jsx
client/store/deck.js

user can make first slide

---

client/components/DeckOverview.jsx

new slide button on deck overview working

---

client/components/NavBar.jsx

FIX(design): Navbar logo is not loading

---

client/components/EditSlideForm.jsx
client/index.scss
package.json

FEAT(slide): Slide edit form has a code editor!

---

client/components/Runkit.jsx
client/index.scss

Default Slideview Live Styles - Grey!
Runkit window has been resized to fit better.
There are still many tweaks to be done to these styles but here is the starter. 
Styles can be modified in the css under the Slideview section.
Alternate Themes can be added by following the same convention I setup (in Slideview Section)
Closes #140

slideview default styles

---

client/components/NavBar.jsx
client/components/user-home.jsx
client/index.scss

FEAT(nav): Make navbar logo clickable

---

client/components/EditSlideForm.jsx
client/index.scss

FEAT(slide): Show deck title on EditSlideForm

---

client/components/NavBar.jsx
client/components/UserDeckList.jsx
client/store/user.js

Removed 'Home' link in navbar, success login points to Deck List Page, relink logo to to Deck List Page
Closes #149

repointing to decklist

---

client/components/DeckOverview.jsx
client/components/DumbDeckForm.jsx
client/components/EditDeckForm.jsx
client/components/NewDeckForm.jsx
client/components/UserDeckList.jsx
client/components/index.jsx
client/index.scss
client/routes.jsx
client/store/deck.js
seed.js

FEAT(deck): User can edit a deck after it has been created

---

client/components/UserDeckList.jsx

FEAT(design): Remove random Bootstrap styles from user deck list

---

client/index.scss

Added one line of code - index.scss
Was not able to test with no footer. (Even if I choose no footer a footer shows up)
Closes #127

footer style

---

client/components/ChatBox.jsx
client/components/SlideViewLive.jsx
client/index.scss
package.json
server/socket/index.js

Presenter chat box

---

client/components/RemoteControl.jsx
client/components/SlideViewLive.jsx
client/components/index.jsx
client/index.scss
client/routes.jsx

Remote control #47

---

client/components/SlideView5.jsx
client/index.scss

FEAT(play):scrolling added but not to slide text because fuck the user

---

client/components/DeckOverview.jsx
client/components/EditSlideForm.jsx
client/index.scss

Closes #133. Closes #171. Closes #97.

Single slide preview #133

---

client/components/DeckOverview.jsx
client/store/chat.js
server/api/decks.js
server/api/slides.js
server/api/users.js

closes #134 closes #156 closes #182

Clear chats #182 also backend security

---

client/components/ChatBox.jsx
client/components/SlideViewLive.jsx
client/index.scss

added in chat styling and for presenter footer with chat

---

client/components/SlideViewFrame.jsx

Closes #198. That is really all.

FIX(design): Wrap slide header in h1

---

client/components/NavBar.jsx

FIX(landing): Link nameplate to home if user is logged out

---

client/components/EditSlideForm.jsx
client/index.scss

Closes #189. Also closes #180, and makes the success toasts disappear after 5 seconds.

Fix edit slide toasts #189

---

client/components/EditSlideForm.jsx
client/components/SlideViewLive.jsx
client/index.scss
package.json

Closes #190. Also closes #186, 'FEAT(remote): Presenter can click a button to e-mail the remote control link to self'.

FEAT(presenter, design): Replace prev/next/exit buttons with Deque buttons

---

client/components/Runkit.jsx
client/socket.js

Runkit sockets #214

---

client/components/DeckOverview.jsx
client/components/EditSlideForm.jsx
client/index.scss

FIX(static): Move navigation buttons up into slide frame

---

server/api/decks.js

added in ordering for chat log

---

client/index.scss

FEAT(design): Make form fields larger

---

client/components/EditDeckForm.jsx
client/components/EditSlideForm.jsx
client/index.scss

Not very lovely, but better than nothing? Closes #188.

FEAT(slide, deck): Add instructions and tool tips to forms

---

client/components/UserDeckList.jsx
client/index.scss

FEAT(design, deck): Change deck list back into links
